spring:
  application:
    name:  gui

  sql:
#    init:
#      schema-locations:
#        - classpath:testdb/schema/schema.sql
#      data-locations:
#        - classpath:testdb/data/data.sql

  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
#      generate-ddl: true
    properties:
      hibernate:
        show_sql: true  # sql ??? ?????.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql ??? ????? ?????

